### ISSUE TITLE
在 openEuler 测试 ROS 小乌龟程序-乌龟无法运动

### ISSUE THREAD

**Issue by Sebastianhayashi** [Sebastianhayashi/ROS-begin#1]
参考该[文章](https://github.com/Sebastianhayashi/ROS-begin/blob/main/%E5%9C%A8%20openEuler%20%E6%B5%8B%E8%AF%95%20ROS%20%E5%B0%8F%E4%B9%8C%E9%BE%9F%E7%A8%8B%E5%BA%8F.md)中最后的“遇到的问题”

问题描述：乌龟无法运动

硬件：QEMU 虚拟机
系统版本：openEuler 24.03
架构：x86

**Comment by Sebastianhayashi** [comment]
log：<img width="1470" alt="Screenshot 2024-07-15 at 14 01 37" src="https://github.com/user-attachments/assets/7388f112-3632-40b0-9e07-608db4a43cf9">

暂未尝试过解决，但是因为服务器原因所以重新安装虚拟机没有进行解决，使用软件源：http://121.36.84.172/dailybuild/EBS-openEuler-24.03-LTS/EBS-openEuler-24.03-LTS/EPOL/multi_version/ROS/humble/x86_64/
该软件源目前（7.16）无法访问

以上 issue 测试时间在 （7.10-7.13）

**Comment by jiuyewxy** [comment]
安一下zlink？
以及把软件源换一下

**Comment by Sebastianhayashi** [comment]
> 安一下zlink？ 以及把软件源换一下

<img width="378" alt="Screenshot 2024-07-16 at 16 46 18" src="https://github.com/user-attachments/assets/725a4fea-daf6-484c-bd71-8766a7332b24">
已安装，问题依旧

**Comment by Sebastianhayashi** [comment]
问题解决：
重新启动后再手动 source 一遍，小乌龟正常移动，问题解决
缺库问题依旧没有解决
